package com.gdufe.osc.dao.mapper.master;

import com.gdufe.osc.entity.DownloadImg;
import com.gdufe.osc.entity.DownloadImgExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface DownloadImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    long countByExample(DownloadImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    int deleteByExample(DownloadImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    int insert(DownloadImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    int insertSelective(DownloadImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    List<DownloadImg> selectByExample(DownloadImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DownloadImg record, @Param("example") DownloadImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_img
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DownloadImg record, @Param("example") DownloadImgExample example);
}