package com.gdufe.osc.dao.mapper.slave;

import com.gdufe.osc.entity.ImgBiZhi;
import com.gdufe.osc.entity.ImgBiZhiExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ImgBiZhiMapperSlave {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    long countByExample(ImgBiZhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    int deleteByExample(ImgBiZhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    int insert(ImgBiZhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    int insertSelective(ImgBiZhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    List<ImgBiZhi> selectByExample(ImgBiZhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImgBiZhi record, @Param("example") ImgBiZhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgBiZhi
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImgBiZhi record, @Param("example") ImgBiZhiExample example);
}